---
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_install:
  - export TZ=Asia/Tokyo
  - gem install bundler -v 2.1.4
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
